export const products = [
  {
    id: 1,
    name: "Oud Al Malaki",
    price: 199,
    originalPrice: 249,
    image: "/product-images/1.webp",
    images: [
      "/product-images/1.webp",
      "/product-images/2.webp",
      "/product-images/3.webp",
    ],
    rating: 4.9,
    reviews: 127,
    category: "oud",
    description: "A majestic blend of pure Cambodian oud with royal saffron",
    longDescription:
      "Experience the pinnacle of luxury with Oud Al Malaki, a fragrance that embodies the essence of Arabian royalty. This exquisite blend features the finest Cambodian oud, carefully aged to perfection and enhanced with precious saffron threads. Each bottle contains the artistry of master perfumers who have crafted this scent to evoke the grandeur of ancient palaces and the mystique of desert nights.",
    topNote: "Saffron, Rose",
    heartNote: "Oud, Amber",
    baseNote: "Sandalwood, Musk",
    featured: true,
    inStock: true,
    size: "50ml",
    sizes: [
      { size: "50ML", price: 199, originalPrice: 249, isDefault: true },
      { size: "100ML", price: 299, originalPrice: 399, isDefault: false },
      { size: "150ML", price: 399, originalPrice: 499, isDefault: false }
    ],
    brand: "Royal Collection",

    slug: "perfume-demo",
    image360: [
      "/360/perfume-demo/1.jpg",
      "/360/perfume-demo/2.jpg",
      "/360/perfume-demo/3.jpg",
      "/360/perfume-demo/4.jpg",
      "/360/perfume-demo/5.jpg",
      "/360/perfume-demo/6.jpg",
      "/360/perfume-demo/7.jpg",
      "/360/perfume-demo/8.jpg",
      "/360/perfume-demo/9.jpg",
      "/360/perfume-demo/10.jpg",
      "/360/perfume-demo/11.jpg",
      "/360/perfume-demo/12.jpg",
      "/360/perfume-demo/13.jpg",
      "/360/perfume-demo/14.jpg",
      "/360/perfume-demo/15.jpg",
      "/360/perfume-demo/16.jpg",
      "/360/perfume-demo/17.jpg",
      "/360/perfume-demo/18.jpg",
      "/360/perfume-demo/19.jpg",
      "/360/perfume-demo/20.jpg",
      "/360/perfume-demo/21.jpg",
      "/360/perfume-demo/22.jpg",
      "/360/perfume-demo/23.jpg",
      "/360/perfume-demo/24.jpg",
      "/360/perfume-demo/25.jpg",
      "/360/perfume-demo/26.jpg",
      "/360/perfume-demo/27.jpg",
      "/360/perfume-demo/28.jpg",
      "/360/perfume-demo/29.jpg",
      "/360/perfume-demo/30.jpg",
      "/360/perfume-demo/31.jpg",
      "/360/perfume-demo/32.jpg",
      "/360/perfume-demo/33.jpg",
      "/360/perfume-demo/34.jpg",
      "/360/perfume-demo/35.jpg",
      "/360/perfume-demo/36.jpg",
    ],
  },
  {
    id: 2,
    name: "Amber Nights",
    price: 199,
    originalPrice: 249,
    image: "/product-images/2.webp",
    images: [
      "/product-images/2.webp",
      "/product-images/3.webp",
      "/product-images/4.webp",
    ],
    rating: 4.7,
    reviews: 89,
    category: "amber",
    description: "Warm amber essence with oriental spices",
    longDescription:
      "Amber Nights captures the warmth and mystery of Arabian evenings. This enchanting fragrance opens with a burst of exotic spices that transport you to bustling souks, while the heart reveals the rich, honeyed depth of amber. Perfect for those who appreciate the traditional art of Middle Eastern perfumery.",
    topNote: "Bergamot, Cardamon",
    heartNote: "Amber, Jasmine",
    baseNote: "Vanilla, Patchouli",
    featured: true,
    inStock: true,
    size: "50ml",
    sizes: [
      { size: "50ML", price: 199, originalPrice: 249, isDefault: true },
      { size: "100ML", price: 299, originalPrice: 399, isDefault: false },
      { size: "150ML", price: 399, originalPrice: 499, isDefault: false }
    ],
    brand: "Desert Collection",

    slug: "perfume-demo",
    image360: [
      "/360/perfume-demo/1.jpg",
      "/360/perfume-demo/2.jpg",
      "/360/perfume-demo/3.jpg",
      "/360/perfume-demo/4.jpg",
      "/360/perfume-demo/5.jpg",
      "/360/perfume-demo/6.jpg",
      "/360/perfume-demo/7.jpg",
      "/360/perfume-demo/8.jpg",
      "/360/perfume-demo/9.jpg",
      "/360/perfume-demo/10.jpg",
      "/360/perfume-demo/11.jpg",
      "/360/perfume-demo/12.jpg",
      "/360/perfume-demo/13.jpg",
      "/360/perfume-demo/14.jpg",
      "/360/perfume-demo/15.jpg",
      "/360/perfume-demo/16.jpg",
      "/360/perfume-demo/17.jpg",
      "/360/perfume-demo/18.jpg",
      "/360/perfume-demo/19.jpg",
      "/360/perfume-demo/20.jpg",
      "/360/perfume-demo/21.jpg",
      "/360/perfume-demo/22.jpg",
      "/360/perfume-demo/23.jpg",
      "/360/perfume-demo/24.jpg",
      "/360/perfume-demo/25.jpg",
      "/360/perfume-demo/26.jpg",
      "/360/perfume-demo/27.jpg",
      "/360/perfume-demo/28.jpg",
      "/360/perfume-demo/29.jpg",
      "/360/perfume-demo/30.jpg",
      "/360/perfume-demo/31.jpg",
      "/360/perfume-demo/32.jpg",
      "/360/perfume-demo/33.jpg",
      "/360/perfume-demo/34.jpg",
      "/360/perfume-demo/35.jpg",
      "/360/perfume-demo/36.jpg",
    ],
  },
  {
    id: 3,
    name: "Desert Rose",
    price: 199,
    originalPrice: 249,
    image: "/product-images/3.webp",
    images: [
      "/product-images/3.webp",
      "/product-images/4.webp",
      "/product-images/5.webp",
    ],
    rating: 4.8,
    reviews: 156,
    category: "floral",
    description: "Exquisite Damascus rose with Arabian frankincense",
    longDescription:
      "Desert Rose is a celebration of femininity and grace, featuring the most precious Damascus roses hand-picked at dawn when their fragrance is most potent. Combined with sacred frankincense from the mountains of Oman, this fragrance tells the story of ancient trade routes and timeless beauty.",
    topNote: "Rose, Lemon",
    heartNote: "Frankincense, Geranium",
    baseNote: "Cedar, White Musk",
    featured: true,
    inStock: true,
    size: "50ml",
    sizes: [
      { size: "50ML", price: 199, originalPrice: 249, isDefault: true },
      { size: "100ML", price: 299, originalPrice: 399, isDefault: false },
      { size: "150ML", price: 399, originalPrice: 499, isDefault: false }
    ],
    brand: "Floral Essence",

    slug: "perfume-demo",
    image360: [
      "/360/perfume-demo/1.jpg",
      "/360/perfume-demo/2.jpg",
      "/360/perfume-demo/3.jpg",
      "/360/perfume-demo/4.jpg",
      "/360/perfume-demo/5.jpg",
      "/360/perfume-demo/6.jpg",
      "/360/perfume-demo/7.jpg",
      "/360/perfume-demo/8.jpg",
      "/360/perfume-demo/9.jpg",
      "/360/perfume-demo/10.jpg",
      "/360/perfume-demo/11.jpg",
      "/360/perfume-demo/12.jpg",
      "/360/perfume-demo/13.jpg",
      "/360/perfume-demo/14.jpg",
      "/360/perfume-demo/15.jpg",
      "/360/perfume-demo/16.jpg",
      "/360/perfume-demo/17.jpg",
      "/360/perfume-demo/18.jpg",
      "/360/perfume-demo/19.jpg",
      "/360/perfume-demo/20.jpg",
      "/360/perfume-demo/21.jpg",
      "/360/perfume-demo/22.jpg",
      "/360/perfume-demo/23.jpg",
      "/360/perfume-demo/24.jpg",
      "/360/perfume-demo/25.jpg",
      "/360/perfume-demo/26.jpg",
      "/360/perfume-demo/27.jpg",
      "/360/perfume-demo/28.jpg",
      "/360/perfume-demo/29.jpg",
      "/360/perfume-demo/30.jpg",
      "/360/perfume-demo/31.jpg",
      "/360/perfume-demo/32.jpg",
      "/360/perfume-demo/33.jpg",
      "/360/perfume-demo/34.jpg",
      "/360/perfume-demo/35.jpg",
      "/360/perfume-demo/36.jpg",
    ],
  },
  {
    id: 4,
    name: "Mystic Saffron",
    price: 199,
    originalPrice: 249,
    image: "/product-images/4.webp",
    images: [
      "/product-images/4.webp",
      "/product-images/5.webp",
      "/product-images/6.webp",
    ],
    rating: 4.9,
    reviews: 203,
    category: "oriental",
    description: "Premium saffron threads with royal oud",
    longDescription:
      "Mystic Saffron represents the ultimate in luxury fragrance, featuring genuine saffron threads worth more than gold. This opulent composition is reserved for those who understand true quality and appreciate the finer things in life. Each spray releases the mystical essence of ancient Persian gardens.",
    topNote: "Saffron, Orange",
    heartNote: "Oud, Cinnamon",
    baseNote: "Leather, Tobacco",
    featured: false,
    inStock: true,
    size: "50ml",
    sizes: [
      { size: "50ML", price: 199, originalPrice: 249, isDefault: true },
      { size: "100ML", price: 299, originalPrice: 399, isDefault: false },
      { size: "150ML", price: 399, originalPrice: 499, isDefault: false }
    ],
    brand: "Luxury Series",

    slug: "perfume-demo",
    image360: [
      "/360/perfume-demo/1.jpg",
      "/360/perfume-demo/2.jpg",
      "/360/perfume-demo/3.jpg",
      "/360/perfume-demo/4.jpg",
      "/360/perfume-demo/5.jpg",
      "/360/perfume-demo/6.jpg",
      "/360/perfume-demo/7.jpg",
      "/360/perfume-demo/8.jpg",
      "/360/perfume-demo/9.jpg",
      "/360/perfume-demo/10.jpg",
      "/360/perfume-demo/11.jpg",
      "/360/perfume-demo/12.jpg",
      "/360/perfume-demo/13.jpg",
      "/360/perfume-demo/14.jpg",
      "/360/perfume-demo/15.jpg",
      "/360/perfume-demo/16.jpg",
      "/360/perfume-demo/17.jpg",
      "/360/perfume-demo/18.jpg",
      "/360/perfume-demo/19.jpg",
      "/360/perfume-demo/20.jpg",
      "/360/perfume-demo/21.jpg",
      "/360/perfume-demo/22.jpg",
      "/360/perfume-demo/23.jpg",
      "/360/perfume-demo/24.jpg",
      "/360/perfume-demo/25.jpg",
      "/360/perfume-demo/26.jpg",
      "/360/perfume-demo/27.jpg",
      "/360/perfume-demo/28.jpg",
      "/360/perfume-demo/29.jpg",
      "/360/perfume-demo/30.jpg",
      "/360/perfume-demo/31.jpg",
      "/360/perfume-demo/32.jpg",
      "/360/perfume-demo/33.jpg",
      "/360/perfume-demo/34.jpg",
      "/360/perfume-demo/35.jpg",
      "/360/perfume-demo/36.jpg",
    ],
  },
  {
    id: 5,
    name: "Musk Al Ghazal",
    price: 199,
    originalPrice: 249,
    image: "/product-images/5.webp",
    images: [
      "/product-images/5.webp",
      "/product-images/6.webp",
      "/product-images/7.webp",
    ],
    rating: 4.6,
    reviews: 74,
    category: "musk",
    description: "Pure white musk with delicate florals",
    longDescription:
      "Musk Al Ghazal offers a pure and ethereal experience, featuring the finest white musk that whispers rather than shouts. This delicate composition is perfect for those who prefer subtle elegance and understand that true luxury lies in restraint and refinement.",
    topNote: "White Musk, Lily",
    heartNote: "Jasmine, Magnolia",
    baseNote: "Sandalwood, Vanilla",
    featured: false,
    inStock: true,
    size: "50ml",
    sizes: [
      { size: "50ML", price: 199, originalPrice: 249, isDefault: true },
      { size: "100ML", price: 299, originalPrice: 399, isDefault: false },
      { size: "150ML", price: 399, originalPrice: 499, isDefault: false }
    ],
    brand: "Pure Collection",

    slug: "perfume-demo",
    image360: [
      "/360/perfume-demo/1.jpg",
      "/360/perfume-demo/2.jpg",
      "/360/perfume-demo/3.jpg",
      "/360/perfume-demo/4.jpg",
      "/360/perfume-demo/5.jpg",
      "/360/perfume-demo/6.jpg",
      "/360/perfume-demo/7.jpg",
      "/360/perfume-demo/8.jpg",
      "/360/perfume-demo/9.jpg",
      "/360/perfume-demo/10.jpg",
      "/360/perfume-demo/11.jpg",
      "/360/perfume-demo/12.jpg",
      "/360/perfume-demo/13.jpg",
      "/360/perfume-demo/14.jpg",
      "/360/perfume-demo/15.jpg",
      "/360/perfume-demo/16.jpg",
      "/360/perfume-demo/17.jpg",
      "/360/perfume-demo/18.jpg",
      "/360/perfume-demo/19.jpg",
      "/360/perfume-demo/20.jpg",
      "/360/perfume-demo/21.jpg",
      "/360/perfume-demo/22.jpg",
      "/360/perfume-demo/23.jpg",
      "/360/perfume-demo/24.jpg",
      "/360/perfume-demo/25.jpg",
      "/360/perfume-demo/26.jpg",
      "/360/perfume-demo/27.jpg",
      "/360/perfume-demo/28.jpg",
      "/360/perfume-demo/29.jpg",
      "/360/perfume-demo/30.jpg",
      "/360/perfume-demo/31.jpg",
      "/360/perfume-demo/32.jpg",
      "/360/perfume-demo/33.jpg",
      "/360/perfume-demo/34.jpg",
      "/360/perfume-demo/35.jpg",
      "/360/perfume-demo/36.jpg",
    ],
  },
  {
    id: 6,
    name: "Royal Attar",
    price: 199,
    originalPrice: 249,
    image: "/product-images/6.webp",
    images: [
      "/product-images/6.webp",
      "/product-images/7.webp",
      "/product-images/8.webp",
    ],
    rating: 5.0,
    reviews: 91,
    category: "attar",
    description: "Traditional attar crafted by master perfumers",
    longDescription:
      "Royal Attar represents centuries of perfumery tradition, handcrafted using ancient techniques passed down through generations of master perfumers. This precious oil-based fragrance concentrates the essence of rare flowers and precious woods into a single, transformative experience.",
    topNote: "Agarwood, Rose",
    heartNote: "Saffron, Amber",
    baseNote: "Musk, Sandalwood",
    featured: false,
    inStock: false,
    size: "50ml",
    sizes: [
      { size: "50ML", price: 199, originalPrice: 249, isDefault: true },
      { size: "100ML", price: 299, originalPrice: 399, isDefault: false },
      { size: "150ML", price: 399, originalPrice: 499, isDefault: false }
    ],
    brand: "Heritage Collection",

    slug: "perfume-demo",
    image360: [
      "/360/perfume-demo/1.jpg",
      "/360/perfume-demo/2.jpg",
      "/360/perfume-demo/3.jpg",
      "/360/perfume-demo/4.jpg",
      "/360/perfume-demo/5.jpg",
      "/360/perfume-demo/6.jpg",
      "/360/perfume-demo/7.jpg",
      "/360/perfume-demo/8.jpg",
      "/360/perfume-demo/9.jpg",
      "/360/perfume-demo/10.jpg",
      "/360/perfume-demo/11.jpg",
      "/360/perfume-demo/12.jpg",
      "/360/perfume-demo/13.jpg",
      "/360/perfume-demo/14.jpg",
      "/360/perfume-demo/15.jpg",
      "/360/perfume-demo/16.jpg",
      "/360/perfume-demo/17.jpg",
      "/360/perfume-demo/18.jpg",
      "/360/perfume-demo/19.jpg",
      "/360/perfume-demo/20.jpg",
      "/360/perfume-demo/21.jpg",
      "/360/perfume-demo/22.jpg",
      "/360/perfume-demo/23.jpg",
      "/360/perfume-demo/24.jpg",
      "/360/perfume-demo/25.jpg",
      "/360/perfume-demo/26.jpg",
      "/360/perfume-demo/27.jpg",
      "/360/perfume-demo/28.jpg",
      "/360/perfume-demo/29.jpg",
      "/360/perfume-demo/30.jpg",
      "/360/perfume-demo/31.jpg",
      "/360/perfume-demo/32.jpg",
      "/360/perfume-demo/33.jpg",
      "/360/perfume-demo/34.jpg",
      "/360/perfume-demo/35.jpg",
      "/360/perfume-demo/36.jpg",
    ],
  },
  {
    id: 7,
    name: "Golden Jasmine",
    price: 199,
    originalPrice: 249,
    image: "/product-images/7.webp",
    images: [
      "/product-images/7.webp",
      "/product-images/8.webp",
      "/product-images/9.webp",
    ],
    rating: 4.5,
    reviews: 112,
    category: "floral",
    description: "Intoxicating jasmine with golden undertones",
    longDescription:
      "Golden Jasmine captures the intoxicating beauty of jasmine flowers blooming under the golden Arabian sun. This luxurious fragrance celebrates the queen of flowers with a composition that is both powerful and delicate, perfect for the confident woman who knows her worth.",
    topNote: "Jasmine, Bergamot",
    heartNote: "Golden Jasmine, Tuberose",
    baseNote: "Amber, White Musk",
    featured: false,
    inStock: true,
    size: "50ml",
    sizes: [
      { size: "50ML", price: 199, originalPrice: 249, isDefault: true },
      { size: "100ML", price: 299, originalPrice: 399, isDefault: false },
      { size: "150ML", price: 399, originalPrice: 499, isDefault: false }
    ],
    brand: "Garden Collection",

    slug: "perfume-demo",
    image360: [
      "/360/perfume-demo/1.jpg",
      "/360/perfume-demo/2.jpg",
      "/360/perfume-demo/3.jpg",
      "/360/perfume-demo/4.jpg",
      "/360/perfume-demo/5.jpg",
      "/360/perfume-demo/6.jpg",
      "/360/perfume-demo/7.jpg",
      "/360/perfume-demo/8.jpg",
      "/360/perfume-demo/9.jpg",
      "/360/perfume-demo/10.jpg",
      "/360/perfume-demo/11.jpg",
      "/360/perfume-demo/12.jpg",
      "/360/perfume-demo/13.jpg",
      "/360/perfume-demo/14.jpg",
      "/360/perfume-demo/15.jpg",
      "/360/perfume-demo/16.jpg",
      "/360/perfume-demo/17.jpg",
      "/360/perfume-demo/18.jpg",
      "/360/perfume-demo/19.jpg",
      "/360/perfume-demo/20.jpg",
      "/360/perfume-demo/21.jpg",
      "/360/perfume-demo/22.jpg",
      "/360/perfume-demo/23.jpg",
      "/360/perfume-demo/24.jpg",
      "/360/perfume-demo/25.jpg",
      "/360/perfume-demo/26.jpg",
      "/360/perfume-demo/27.jpg",
      "/360/perfume-demo/28.jpg",
      "/360/perfume-demo/29.jpg",
      "/360/perfume-demo/30.jpg",
      "/360/perfume-demo/31.jpg",
      "/360/perfume-demo/32.jpg",
      "/360/perfume-demo/33.jpg",
      "/360/perfume-demo/34.jpg",
      "/360/perfume-demo/35.jpg",
      "/360/perfume-demo/36.jpg",
    ],
  },
  {
    id: 8,
    name: "Black Oud Intense",
    price: 199,
    originalPrice: 249,
    image: "/product-images/8.webp",
    images: [
      "/product-images/8.webp",
      "/product-images/9.webp",
      "/product-images/1.webp",
    ],
    rating: 4.9,
    reviews: 67,
    category: "oud",
    description: "Intense black oud with smoky accords",
    longDescription:
      "Black Oud Intense is for the connoisseur who demands nothing but the finest. This powerful composition features rare black oud aged in traditional wooden barrels, creating a smoky, mysterious fragrance that commands attention and respect.",
    topNote: "Black Pepper, Incense",
    heartNote: "Black Oud, Smoke",
    baseNote: "Leather, Dark Amber",
    featured: false,
    inStock: true,
    size: "50ml",
    sizes: [
      { size: "50ML", price: 199, originalPrice: 249, isDefault: true },
      { size: "100ML", price: 299, originalPrice: 399, isDefault: false },
      { size: "150ML", price: 399, originalPrice: 499, isDefault: false }
    ],
    brand: "Intense Collection",

    slug: "perfume-demo",
    image360: [
      "/360/perfume-demo/1.jpg",
      "/360/perfume-demo/2.jpg",
      "/360/perfume-demo/3.jpg",
      "/360/perfume-demo/4.jpg",
      "/360/perfume-demo/5.jpg",
      "/360/perfume-demo/6.jpg",
      "/360/perfume-demo/7.jpg",
      "/360/perfume-demo/8.jpg",
      "/360/perfume-demo/9.jpg",
      "/360/perfume-demo/10.jpg",
      "/360/perfume-demo/11.jpg",
      "/360/perfume-demo/12.jpg",
      "/360/perfume-demo/13.jpg",
      "/360/perfume-demo/14.jpg",
      "/360/perfume-demo/15.jpg",
      "/360/perfume-demo/16.jpg",
      "/360/perfume-demo/17.jpg",
      "/360/perfume-demo/18.jpg",
      "/360/perfume-demo/19.jpg",
      "/360/perfume-demo/20.jpg",
      "/360/perfume-demo/21.jpg",
      "/360/perfume-demo/22.jpg",
      "/360/perfume-demo/23.jpg",
      "/360/perfume-demo/24.jpg",
      "/360/perfume-demo/25.jpg",
      "/360/perfume-demo/26.jpg",
      "/360/perfume-demo/27.jpg",
      "/360/perfume-demo/28.jpg",
      "/360/perfume-demo/29.jpg",
      "/360/perfume-demo/30.jpg",
      "/360/perfume-demo/31.jpg",
      "/360/perfume-demo/32.jpg",
      "/360/perfume-demo/33.jpg",
      "/360/perfume-demo/34.jpg",
      "/360/perfume-demo/35.jpg",
      "/360/perfume-demo/36.jpg",
    ],
  },
];

export const categories = [
  { id: "all", name: "All Products", count: products.length },
  {
    id: "oud",
    name: "Oud",
    count: products.filter((p) => p.category === "oud").length,
  },
  {
    id: "amber",
    name: "Amber",
    count: products.filter((p) => p.category === "amber").length,
  },
  {
    id: "floral",
    name: "Floral",
    count: products.filter((p) => p.category === "floral").length,
  },
  {
    id: "oriental",
    name: "Oriental",
    count: products.filter((p) => p.category === "oriental").length,
  },
  {
    id: "musk",
    name: "Musk",
    count: products.filter((p) => p.category === "musk").length,
  },
  {
    id: "attar",
    name: "Attar",
    count: products.filter((p) => p.category === "attar").length,
  },
];

export const featuredProducts = products.filter((p) => p.featured);

export const getProductById = (id) => {
  return products.find((product) => product.id === parseInt(id));
};

export const getProductsByCategory = (category) => {
  if (category === "all") return products;
  return products.filter((product) => product.category === category);
};

// Essential Oils Product Data
export const oils = [
  {
    id: 101,
    name: "Lavender Dreams Oil",
    price: 89,
    originalPrice: 109,
    image: "/product-images/1.webp",
    images: [
      "/product-images/1.webp",
      "/product-images/2.webp",
      "/product-images/3.webp",
    ],
    rating: 4.8,
    reviews: 156,
    category: "oil",
    subcategory: "floral",
    description: "Pure lavender essential oil for relaxation and calm",
    longDescription:
      "Our Lavender Dreams Oil is extracted from the finest French lavender fields in Provence. This premium essential oil promotes deep relaxation, reduces stress, and helps create a peaceful atmosphere. Perfect for aromatherapy, massage, or adding to your diffuser for a calming bedtime routine.",
    benefits: "Relaxation, Sleep Aid,Stress Relief, Stress Relief",
    usage: "Aromatherapy, Massage, Diffuser",
    origin: "France (Provence)",
    featured: true,
    inStock: true,
    size: "30ml",
    sizes: [
      { size: "15ML", price: 49, originalPrice: 59, isDefault: false },
      { size: "30ML", price: 89, originalPrice: 109, isDefault: true },
      { size: "50ML", price: 139, originalPrice: 169, isDefault: false }
    ],
    brand: "Pure Essence",
    purity: "100% Pure",
    extraction: "Steam Distilled",
    slug: "lavender-dreams-oil",
  },
  {
    id: 102,
    name: "Eucalyptus Fresh Oil",
    price: 95,
    originalPrice: 119,
    image: "/product-images/2.webp",
    images: [
      "/product-images/2.webp",
      "/product-images/3.webp",
      "/product-images/4.webp",
    ],
    rating: 4.7,
    reviews: 203,
    category: "oil",
    subcategory: "medicinal",
    description: "Refreshing eucalyptus oil for respiratory wellness",
    longDescription:
      "Eucalyptus Fresh Oil is sourced from premium Australian eucalyptus trees. Known for its invigorating and clearing properties, this oil helps support respiratory health while providing an energizing and refreshing experience. Ideal for steam inhalation or diffusing during cold seasons.",
    benefits: "Respiratory Support, Energy Boost, Mental Clarity",
    usage: "Inhalation, Diffuser, Chest Rub",
    origin: "Australia",
    featured: true,
    inStock: true,
    size: "30ml",
    sizes: [
      { size: "15ML", price: 52, originalPrice: 62, isDefault: false },
      { size: "30ML", price: 95, originalPrice: 119, isDefault: true },
      { size: "50ML", price: 149, originalPrice: 179, isDefault: false }
    ],
    brand: "Nature's Breath",
    purity: "100% Pure",
    extraction: "Steam Distilled",
    slug: "eucalyptus-fresh-oil",
  },
  {
    id: 103,
    name: "Peppermint Energize Oil",
    price: 79,
    originalPrice: 99,
    image: "/product-images/3.webp",
    images: [
      "/product-images/3.webp",
      "/product-images/4.webp",
      "/product-images/5.webp",
    ],
    rating: 4.9,
    reviews: 287,
    category: "oil",
    subcategory: "energizing",
    description: "Invigorating peppermint oil for focus and energy",
    longDescription:
      "Peppermint Energize Oil delivers a powerful burst of natural energy and mental clarity. Sourced from organic peppermint farms, this cooling oil helps enhance focus, reduce fatigue, and provides a refreshing sensation. Perfect for morning routines or when you need an afternoon pick-me-up.",
    benefits: "Mental Focus, Energy Boost, Cooling Effect",
    usage: "Diffuser, Topical (diluted), Inhalation",
    origin: "Oregon, USA",
    featured: true,
    inStock: true,
    size: "30ml",
    sizes: [
      { size: "15ML", price: 45, originalPrice: 55, isDefault: false },
      { size: "30ML", price: 79, originalPrice: 99, isDefault: true },
      { size: "50ML", price: 125, originalPrice: 149, isDefault: false }
    ],
    brand: "Mint Masters",
    purity: "100% Pure Organic",
    extraction: "Steam Distilled",
    slug: "peppermint-energize-oil",
  },
  {
    id: 104,
    name: "Tea Tree Healing Oil",
    price: 85,
    originalPrice: 105,
    image: "/product-images/4.webp",
    images: [
      "/product-images/4.webp",
      "/product-images/5.webp",
      "/product-images/6.webp",
    ],
    rating: 4.6,
    reviews: 198,
    category: "oil",
    subcategory: "medicinal",
    description: "Pure tea tree oil with natural antimicrobial properties",
    longDescription:
      "Tea Tree Healing Oil is sourced from native Australian Melaleuca trees. Known for its powerful antimicrobial and purifying properties, this oil is perfect for skincare routines, natural cleaning, and creating a fresh, clean atmosphere in your home.",
    benefits: "Antimicrobial, Skin Care, Air Purification",
    usage: "Topical (diluted), Diffuser, Cleaning",
    origin: "Australia",
    featured: false,
    inStock: true,
    size: "30ml",
    sizes: [
      { size: "15ML", price: 48, originalPrice: 58, isDefault: false },
      { size: "30ML", price: 85, originalPrice: 105, isDefault: true },
      { size: "50ML", price: 135, originalPrice: 159, isDefault: false }
    ],
    brand: "Aussie Pure",
    purity: "100% Pure",
    extraction: "Steam Distilled",
    slug: "tea-tree-healing-oil",
  },
  {
    id: 105,
    name: "Sweet Orange Bliss Oil",
    price: 69,
    originalPrice: 89,
    image: "/product-images/5.webp",
    images: [
      "/product-images/5.webp",
      "/product-images/6.webp",
      "/product-images/7.webp",
    ],
    rating: 4.5,
    reviews: 143,
    category: "oil",
    subcategory: "citrus",
    description: "Uplifting sweet orange oil for mood enhancement",
    longDescription:
      "Sweet Orange Bliss Oil brings sunshine to any day with its cheerful, uplifting aroma. Cold-pressed from fresh orange peels, this oil naturally boosts mood, reduces stress, and creates a warm, welcoming atmosphere. Perfect for brightening your space and lifting your spirits.",
    benefits: "Mood Enhancement, Stress Relief, Energy Boost",
    usage: "Diffuser, Massage (diluted), Room Spray",
    origin: "California, USA",
    featured: false,
    inStock: true,
    size: "30ml",
    sizes: [
      { size: "15ML", price: 39, originalPrice: 49, isDefault: false },
      { size: "30ML", price: 69, originalPrice: 89, isDefault: true },
      { size: "50ML", price: 109, originalPrice: 129, isDefault: false }
    ],
    brand: "Citrus Grove",
    purity: "100% Pure",
    extraction: "Cold Pressed",
    slug: "sweet-orange-bliss-oil",
  },
  {
    id: 106,
    name: "Frankincense Sacred Oil",
    price: 159,
    originalPrice: 199,
    image: "/product-images/6.webp",
    images: [
      "/product-images/6.webp",
      "/product-images/7.webp",
      "/product-images/8.webp",
    ],
    rating: 5.0,
    reviews: 89,
    category: "oil",
    subcategory: "spiritual",
    description: "Premium frankincense oil for meditation and spirituality",
    longDescription:
      "Frankincense Sacred Oil is harvested from ancient Boswellia trees in Oman. This precious oil has been treasured for thousands of years for its spiritual and meditative properties. Its rich, woody aroma promotes deep relaxation, enhances meditation, and creates a sacred atmosphere.",
    benefits: "Meditation Support, Spiritual Practice, Anti-aging",
    usage: "Meditation, Skincare (diluted), Diffuser",
    origin: "Oman",
    featured: false,
    inStock: true,
    size: "15ml",
    sizes: [
      { size: "5ML", price: 89, originalPrice: 109, isDefault: false },
      { size: "15ML", price: 159, originalPrice: 199, isDefault: true },
      { size: "30ML", price: 299, originalPrice: 359, isDefault: false }
    ],
    brand: "Sacred Essence",
    purity: "100% Pure",
    extraction: "Steam Distilled",
    slug: "frankincense-sacred-oil",
  }
];

// Diffusers Product Data
export const diffusers = [
  {
    id: 201,
    name: "Zen Ultrasonic Diffuser",
    price: 149,
    originalPrice: 199,
    image: "/product-images/1.webp",
    images: [
      "/product-images/1.webp",
      "/product-images/2.webp",
      "/product-images/3.webp",
    ],
    rating: 4.8,
    reviews: 234,
    category: "diffuser",
    subcategory: "ultrasonic",
    description: "Premium ultrasonic diffuser with LED mood lighting",
    longDescription:
      "The Zen Ultrasonic Diffuser combines advanced ultrasonic technology with elegant design. Featuring multiple mist modes, timer settings, and soothing LED lights, this diffuser creates the perfect ambiance for relaxation. Its whisper-quiet operation makes it ideal for bedrooms, offices, or meditation spaces.",
    capacity: "300ml",
    coverage: "Up to 500 sq ft",
    runtime: "Up to 10 hours",
    features: "LED Lights, Timer, Auto Shut-off,Whisper-quiet operation",
    featured: true,
    inStock: true,
    color: "White Oak",
    colors: [
      { color: "White Oak", price: 149, originalPrice: 199, isDefault: true },
      { color: "Dark Walnut", price: 159, originalPrice: 209, isDefault: false },
      { color: "Bamboo", price: 149, originalPrice: 199, isDefault: false }
    ],
    brand: "ZenHome",
    warranty: "2 Years",
    powerSource: "AC Adapter",
    slug: "zen-ultrasonic-diffuser",
  },
  {
    id: 202,
    name: "Aurora Nebulizing Diffuser",
    price: 299,
    originalPrice: 379,
    image: "/product-images/2.webp",
    images: [
      "/product-images/2.webp",
      "/product-images/3.webp",
      "/product-images/4.webp",
    ],
    rating: 4.9,
    reviews: 167,
    category: "diffuser",
    subcategory: "nebulizing",
    description: "Professional nebulizing diffuser for maximum potency",
    longDescription:
      "The Aurora Nebulizing Diffuser uses advanced atomization technology to deliver pure essential oils without heat or water. This preserves the oils' therapeutic properties while providing the strongest scent throw. Perfect for large spaces and therapeutic applications.",
    capacity: "N/A (No Water)",
    coverage: "Up to 1000 sq ft",
    runtime: "Intermittent Operation",
    features: "Pure Oil Diffusion, Adjustable Output, Timer",
    featured: true,
    inStock: true,
    color: "Brushed Silver",
    colors: [
      { color: "Brushed Silver", price: 299, originalPrice: 379, isDefault: true },
      { color: "Matte Black", price: 309, originalPrice: 389, isDefault: false },
      { color: "Rose Gold", price: 319, originalPrice: 399, isDefault: false }
    ],
    brand: "AromaTech Pro",
    warranty: "3 Years",
    powerSource: "AC Adapter",
    slug: "aurora-nebulizing-diffuser",
  },
  {
    id: 203,
    name: "Crystal Harmony Diffuser",
    price: 89,
    originalPrice: 119,
    image: "/product-images/3.webp",
    images: [
      "/product-images/3.webp",
      "/product-images/4.webp",
      "/product-images/5.webp",
    ],
    rating: 4.6,
    reviews: 298,
    category: "diffuser",
    subcategory: "ultrasonic",
    description: "Compact crystal-inspired diffuser perfect for small spaces",
    longDescription:
      "The Crystal Harmony Diffuser features a stunning crystal-inspired design that doubles as home decor. Its compact size makes it perfect for desks, nightstands, or small rooms. With color-changing LED lights and multiple timer options, it creates a beautiful and aromatic environment.",
    capacity: "150ml",
    coverage: "Up to 200 sq ft",
    runtime: "Up to 6 hours",
    features: "Color-changing LEDs, Compact Design, Silent Operation",
    featured: true,
    inStock: true,
    color: "Clear Crystal",
    colors: [
      { color: "Clear Crystal", price: 89, originalPrice: 119, isDefault: true },
      { color: "Smoky Quartz", price: 89, originalPrice: 119, isDefault: false },
      { color: "Rose Quartz", price: 95, originalPrice: 125, isDefault: false }
    ],
    brand: "CrystalMist",
    warranty: "1 Year",
    powerSource: "USB/AC Adapter",
    slug: "crystal-harmony-diffuser",
  },
  {
    id: 204,
    name: "Smart WiFi Aroma Diffuser",
    price: 199,
    originalPrice: 249,
    image: "/product-images/4.webp",
    images: [
      "/product-images/4.webp",
      "/product-images/5.webp",
      "/product-images/6.webp",
    ],
    rating: 4.7,
    reviews: 189,
    category: "diffuser",
    subcategory: "smart",
    description: "WiFi-enabled smart diffuser with app control.Perfect for smart home.",
    longDescription:
      "Control your aromatherapy experience from anywhere with the Smart WiFi Aroma Diffuser. Compatible with smartphones and voice assistants, this intelligent diffuser allows you to schedule sessions, adjust settings, and monitor usage remotely. Perfect for the modern smart home.",
    capacity: "400ml",
    coverage: "Up to 600 sq ft",
    runtime: "Up to 12 hours",
    features: "WiFi Control, App Integration, Voice Command, Scheduling",
    featured: false,
    inStock: true,
    color: "Sleek Black",
    colors: [
      { color: "Sleek Black", price: 199, originalPrice: 249, isDefault: true },
      { color: "Pure White", price: 199, originalPrice: 249, isDefault: false },
      { color: "Space Gray", price: 209, originalPrice: 259, isDefault: false }
    ],
    brand: "SmartScent",
    warranty: "2 Years",
    powerSource: "AC Adapter",
    slug: "smart-wifi-aroma-diffuser",
  },
  {
    id: 205,
    name: "Vintage Reed Diffuser Set",
    price: 79,
    originalPrice: 99,
    image: "/product-images/5.webp",
    images: [
      "/product-images/5.webp",
      "/product-images/6.webp",
      "/product-images/7.webp",
    ],
    rating: 4.4,
    reviews: 145,
    category: "diffuser",
    subcategory: "reed",
    description: "Elegant reed diffuser set with natural bamboo reeds",
    longDescription:
      "The Vintage Reed Diffuser Set brings timeless elegance to any space. This passive diffusion system uses natural bamboo reeds to slowly release fragrance for weeks. No electricity required, making it perfect for bathrooms, closets, or anywhere you want continuous, subtle scenting.",
    capacity: "200ml Fragrance Oil",
    coverage: "Up to 300 sq ft",
    runtime: "6-8 weeks",
    features: "No Power Required, Continuous Scenting, Decorative Design",
    featured: false,
    inStock: true,
    color: "Amber Glass",
    colors: [
      { color: "Amber Glass", price: 79, originalPrice: 99, isDefault: true },
      { color: "Clear Glass", price: 75, originalPrice: 95, isDefault: false },
      { color: "Frosted Glass", price: 85, originalPrice: 105, isDefault: false }
    ],
    brand: "Heritage Home",
    warranty: "N/A",
    powerSource: "None Required",
    slug: "vintage-reed-diffuser-set",
  },
  {
    id: 206,
    name: "Car Essential Oil Diffuser",
    price: 45,
    originalPrice: 59,
    image: "/product-images/6.webp",
    images: [
      "/product-images/6.webp",
      "/product-images/7.webp",
      "/product-images/8.webp",
    ],
    rating: 4.3,
    reviews: 321,
    category: "diffuser",
    subcategory: "portable",
    description: "Portable car diffuser for aromatherapy on the go",
    longDescription:
      "Transform your daily commute with the Car Essential Oil Diffuser. This compact, portable diffuser plugs into your car's USB port and creates a pleasant, therapeutic environment while driving. Features include adjustable mist output and LED indicators.",
    capacity: "50ml",
    coverage: "Car Interior",
    runtime: "Up to 8 hours",
    features: "USB Powered, Portable, LED Indicator, Car Mount",
    featured: false,
    inStock: true,
    color: "Midnight Black",
    colors: [
      { color: "Midnight Black", price: 45, originalPrice: 59, isDefault: true },
      { color: "Silver Chrome", price: 45, originalPrice: 59, isDefault: false },
      { color: "Wood Grain", price: 49, originalPrice: 63, isDefault: false }
    ],
    brand: "DriveZen",
    warranty: "1 Year",
    powerSource: "USB (12V)",
    slug: "car-essential-oil-diffuser",
  }
];

// Combined categories for oils and diffusers
export const oilsDiffusersCategories = [
  { id: "all", name: "All Products", count: oils.length + diffusers.length },
  { id: "oil", name: "Essential Oils", count: oils.length },
  { id: "diffuser", name: "Diffusers", count: diffusers.length },
];

// Featured products from both oils and diffusers
export const featuredOilsDiffusers = [...oils.filter(p => p.featured), ...diffusers.filter(p => p.featured)];

// Helper functions
export const getOilById = (id) => {
  return oils.find((oil) => oil.id === parseInt(id));
};

export const getDiffuserById = (id) => {
  return diffusers.find((diffuser) => diffuser.id === parseInt(id));
};

export const getOilsBySubcategory = (subcategory) => {
  return oils.filter((oil) => oil.subcategory === subcategory);
};

export const getDiffusersBySubcategory = (subcategory) => {
  return diffusers.filter((diffuser) => diffuser.subcategory === subcategory);
};